export const CHANGE_TOP_BANNERS = "CHANGE_TOP_BANNERS";
export const CHANGE_HOT_RECOMMENDS = "CHANGE_HOT_RECOMMENDS";
export const CHANGE_NEW_ALBUM = "CHANGE_NEW_ALBUM";

export const CHANGE_IMPOVE_RANKING = "CHANGE_IMPOVE_RANKING";
export const CHANGE_NEW_SONGS_RANKING = "CHANGE_NEW_SONGS_RANKING";
export const CHANGE_CREATOR_RANKING = "CHANGE_CREATOR_RANKING";


